{% set name = "sqlalchemy-risingwave" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-risingwave-{{ version }}.tar.gz
  sha256: 07ce402a66502dcbdbbb16059f39fac6035c5f6911cd577ebedbd76eba558efe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.4,<2

test:
  imports:
    - sqlalchemy_risingwave
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/risingwavelabs/risingwave
  summary: RisingWave dialect for SQLAlchemy
  dev_url: https://github.com/risingwavelabs/sqlalchemy-risingwave
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - KeXiangWang
